// Automatically generated by makemoduledefs.py.

#include "py/mpconfig.h"
#if (CIRCUITPY_FUTURE)
    extern const struct _mp_obj_module_t future_module;
    #define MODULE_DEF_MP_QSTR___FUTURE__ { MP_ROM_QSTR(MP_QSTR___future__), MP_ROM_PTR(&future_module) },
#else
    #define MODULE_DEF_MP_QSTR___FUTURE__
#endif

#if (MICROPY_PY_UASYNCIO)
    extern const struct _mp_obj_module_t mp_module_uasyncio;
    #define MODULE_DEF_MP_QSTR__ASYNCIO { MP_ROM_QSTR(MP_QSTR__asyncio), MP_ROM_PTR(&mp_module_uasyncio) },
#else
    #define MODULE_DEF_MP_QSTR__ASYNCIO
#endif

#if (CIRCUITPY_BLEIO)
    extern const struct _mp_obj_module_t bleio_module;
    #define MODULE_DEF_MP_QSTR__BLEIO { MP_ROM_QSTR(MP_QSTR__bleio), MP_ROM_PTR(&bleio_module) },
#else
    #define MODULE_DEF_MP_QSTR__BLEIO
#endif

#if (CIRCUITPY__EVE)
    extern const struct _mp_obj_module_t _eve_module;
    #define MODULE_DEF_MP_QSTR__EVE { MP_ROM_QSTR(MP_QSTR__eve), MP_ROM_PTR(&_eve_module) },
#else
    #define MODULE_DEF_MP_QSTR__EVE
#endif

#if (CIRCUITPY_BUSDEVICE)
    extern const struct _mp_obj_module_t adafruit_bus_device_module;
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE { MP_ROM_QSTR(MP_QSTR_adafruit_bus_device), MP_ROM_PTR(&adafruit_bus_device_module) },
#else
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE
#endif

#if (CIRCUITPY_BUSDEVICE)
    extern const struct _mp_obj_module_t adafruit_bus_device_i2c_device_module;
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE_DOT_I2C_DEVICE { MP_ROM_QSTR(MP_QSTR_adafruit_bus_device_dot_i2c_device), MP_ROM_PTR(&adafruit_bus_device_i2c_device_module) },
#else
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE_DOT_I2C_DEVICE
#endif

#if (CIRCUITPY_BUSDEVICE)
    extern const struct _mp_obj_module_t adafruit_bus_device_spi_device_module;
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE_DOT_SPI_DEVICE { MP_ROM_QSTR(MP_QSTR_adafruit_bus_device_dot_spi_device), MP_ROM_PTR(&adafruit_bus_device_spi_device_module) },
#else
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE_DOT_SPI_DEVICE
#endif

#if (CIRCUITPY_PIXELBUF)
    extern const struct _mp_obj_module_t pixelbuf_module;
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_PIXELBUF { MP_ROM_QSTR(MP_QSTR_adafruit_pixelbuf), MP_ROM_PTR(&pixelbuf_module) },
#else
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_PIXELBUF
#endif

#if (CIRCUITPY_AESIO)
    extern const struct _mp_obj_module_t aesio_module;
    #define MODULE_DEF_MP_QSTR_AESIO { MP_ROM_QSTR(MP_QSTR_aesio), MP_ROM_PTR(&aesio_module) },
#else
    #define MODULE_DEF_MP_QSTR_AESIO
#endif

#if (CIRCUITPY_ALARM)
    extern const struct _mp_obj_module_t alarm_module;
    #define MODULE_DEF_MP_QSTR_ALARM { MP_ROM_QSTR(MP_QSTR_alarm), MP_ROM_PTR(&alarm_module) },
#else
    #define MODULE_DEF_MP_QSTR_ALARM
#endif

#if (CIRCUITPY_ANALOGIO)
    extern const struct _mp_obj_module_t analogio_module;
    #define MODULE_DEF_MP_QSTR_ANALOGIO { MP_ROM_QSTR(MP_QSTR_analogio), MP_ROM_PTR(&analogio_module) },
#else
    #define MODULE_DEF_MP_QSTR_ANALOGIO
#endif

#if (MICROPY_PY_ARRAY)
    extern const struct _mp_obj_module_t mp_module_array;
    #define MODULE_DEF_MP_QSTR_ARRAY { MP_ROM_QSTR(MP_QSTR_array), MP_ROM_PTR(&mp_module_array) },
#else
    #define MODULE_DEF_MP_QSTR_ARRAY
#endif

#if (CIRCUITPY_ATEXIT)
    extern const struct _mp_obj_module_t atexit_module;
    #define MODULE_DEF_MP_QSTR_ATEXIT { MP_ROM_QSTR(MP_QSTR_atexit), MP_ROM_PTR(&atexit_module) },
#else
    #define MODULE_DEF_MP_QSTR_ATEXIT
#endif

#if (CIRCUITPY_AUDIOBUSIO)
    extern const struct _mp_obj_module_t audiobusio_module;
    #define MODULE_DEF_MP_QSTR_AUDIOBUSIO { MP_ROM_QSTR(MP_QSTR_audiobusio), MP_ROM_PTR(&audiobusio_module) },
#else
    #define MODULE_DEF_MP_QSTR_AUDIOBUSIO
#endif

#if (CIRCUITPY_AUDIOCORE)
    extern const struct _mp_obj_module_t audiocore_module;
    #define MODULE_DEF_MP_QSTR_AUDIOCORE { MP_ROM_QSTR(MP_QSTR_audiocore), MP_ROM_PTR(&audiocore_module) },
#else
    #define MODULE_DEF_MP_QSTR_AUDIOCORE
#endif

#if (CIRCUITPY_AUDIOMIXER)
    extern const struct _mp_obj_module_t audiomixer_module;
    #define MODULE_DEF_MP_QSTR_AUDIOMIXER { MP_ROM_QSTR(MP_QSTR_audiomixer), MP_ROM_PTR(&audiomixer_module) },
#else
    #define MODULE_DEF_MP_QSTR_AUDIOMIXER
#endif

#if (CIRCUITPY_AUDIOMP3)
    extern const struct _mp_obj_module_t audiomp3_module;
    #define MODULE_DEF_MP_QSTR_AUDIOMP3 { MP_ROM_QSTR(MP_QSTR_audiomp3), MP_ROM_PTR(&audiomp3_module) },
#else
    #define MODULE_DEF_MP_QSTR_AUDIOMP3
#endif

#if (CIRCUITPY_AUDIOPWMIO)
    extern const struct _mp_obj_module_t audiopwmio_module;
    #define MODULE_DEF_MP_QSTR_AUDIOPWMIO { MP_ROM_QSTR(MP_QSTR_audiopwmio), MP_ROM_PTR(&audiopwmio_module) },
#else
    #define MODULE_DEF_MP_QSTR_AUDIOPWMIO
#endif

#if (MICROPY_PY_UBINASCII)
    extern const struct _mp_obj_module_t mp_module_ubinascii;
    #define MODULE_DEF_MP_QSTR_BINASCII { MP_ROM_QSTR(MP_QSTR_binascii), MP_ROM_PTR(&mp_module_ubinascii) },
#else
    #define MODULE_DEF_MP_QSTR_BINASCII
#endif

#if (CIRCUITPY_BITBANGIO)
    extern const struct _mp_obj_module_t bitbangio_module;
    #define MODULE_DEF_MP_QSTR_BITBANGIO { MP_ROM_QSTR(MP_QSTR_bitbangio), MP_ROM_PTR(&bitbangio_module) },
#else
    #define MODULE_DEF_MP_QSTR_BITBANGIO
#endif

#if (CIRCUITPY_BITMAPTOOLS)
    extern const struct _mp_obj_module_t bitmaptools_module;
    #define MODULE_DEF_MP_QSTR_BITMAPTOOLS { MP_ROM_QSTR(MP_QSTR_bitmaptools), MP_ROM_PTR(&bitmaptools_module) },
#else
    #define MODULE_DEF_MP_QSTR_BITMAPTOOLS
#endif

#if (CIRCUITPY_BITOPS)
    extern const struct _mp_obj_module_t bitops_module;
    #define MODULE_DEF_MP_QSTR_BITOPS { MP_ROM_QSTR(MP_QSTR_bitops), MP_ROM_PTR(&bitops_module) },
#else
    #define MODULE_DEF_MP_QSTR_BITOPS
#endif

#if (CIRCUITPY_BOARD)
    extern const struct _mp_obj_module_t board_module;
    #define MODULE_DEF_MP_QSTR_BOARD { MP_ROM_QSTR(MP_QSTR_board), MP_ROM_PTR(&board_module) },
#else
    #define MODULE_DEF_MP_QSTR_BOARD
#endif

#if (CIRCUITPY_BUSIO)
    extern const struct _mp_obj_module_t busio_module;
    #define MODULE_DEF_MP_QSTR_BUSIO { MP_ROM_QSTR(MP_QSTR_busio), MP_ROM_PTR(&busio_module) },
#else
    #define MODULE_DEF_MP_QSTR_BUSIO
#endif

#if (CIRCUITPY_COUNTIO)
    extern const struct _mp_obj_module_t countio_module;
    #define MODULE_DEF_MP_QSTR_COUNTIO { MP_ROM_QSTR(MP_QSTR_countio), MP_ROM_PTR(&countio_module) },
#else
    #define MODULE_DEF_MP_QSTR_COUNTIO
#endif

#if (CIRCUITPY_DIGITALIO)
    extern const struct _mp_obj_module_t digitalio_module;
    #define MODULE_DEF_MP_QSTR_DIGITALIO { MP_ROM_QSTR(MP_QSTR_digitalio), MP_ROM_PTR(&digitalio_module) },
#else
    #define MODULE_DEF_MP_QSTR_DIGITALIO
#endif

#if (CIRCUITPY_DISPLAYIO)
    extern const struct _mp_obj_module_t displayio_module;
    #define MODULE_DEF_MP_QSTR_DISPLAYIO { MP_ROM_QSTR(MP_QSTR_displayio), MP_ROM_PTR(&displayio_module) },
#else
    #define MODULE_DEF_MP_QSTR_DISPLAYIO
#endif

#if (MICROPY_PY_UERRNO)
    extern const struct _mp_obj_module_t mp_module_uerrno;
    #define MODULE_DEF_MP_QSTR_ERRNO { MP_ROM_QSTR(MP_QSTR_errno), MP_ROM_PTR(&mp_module_uerrno) },
#else
    #define MODULE_DEF_MP_QSTR_ERRNO
#endif

#if (CIRCUITPY_FLOPPYIO)
    extern const struct _mp_obj_module_t floppyio_module;
    #define MODULE_DEF_MP_QSTR_FLOPPYIO { MP_ROM_QSTR(MP_QSTR_floppyio), MP_ROM_PTR(&floppyio_module) },
#else
    #define MODULE_DEF_MP_QSTR_FLOPPYIO
#endif

#if (CIRCUITPY_DISPLAYIO && CIRCUITPY_TERMINALIO)
    extern const struct _mp_obj_module_t fontio_module;
    #define MODULE_DEF_MP_QSTR_FONTIO { MP_ROM_QSTR(MP_QSTR_fontio), MP_ROM_PTR(&fontio_module) },
#else
    #define MODULE_DEF_MP_QSTR_FONTIO
#endif

#if (CIRCUITPY_FRAMEBUFFERIO)
    extern const struct _mp_obj_module_t framebufferio_module;
    #define MODULE_DEF_MP_QSTR_FRAMEBUFFERIO { MP_ROM_QSTR(MP_QSTR_framebufferio), MP_ROM_PTR(&framebufferio_module) },
#else
    #define MODULE_DEF_MP_QSTR_FRAMEBUFFERIO
#endif

#if (CIRCUITPY_GETPASS)
    extern const struct _mp_obj_module_t getpass_module;
    #define MODULE_DEF_MP_QSTR_GETPASS { MP_ROM_QSTR(MP_QSTR_getpass), MP_ROM_PTR(&getpass_module) },
#else
    #define MODULE_DEF_MP_QSTR_GETPASS
#endif

#if (CIRCUITPY_GIFIO)
    extern const struct _mp_obj_module_t gifio_module;
    #define MODULE_DEF_MP_QSTR_GIFIO { MP_ROM_QSTR(MP_QSTR_gifio), MP_ROM_PTR(&gifio_module) },
#else
    #define MODULE_DEF_MP_QSTR_GIFIO
#endif

#if (CIRCUITPY_IMAGECAPTURE)
    extern const struct _mp_obj_module_t imagecapture_module;
    #define MODULE_DEF_MP_QSTR_IMAGECAPTURE { MP_ROM_QSTR(MP_QSTR_imagecapture), MP_ROM_PTR(&imagecapture_module) },
#else
    #define MODULE_DEF_MP_QSTR_IMAGECAPTURE
#endif

#if (MICROPY_PY_UJSON)
    extern const struct _mp_obj_module_t mp_module_ujson;
    #define MODULE_DEF_MP_QSTR_JSON { MP_ROM_QSTR(MP_QSTR_json), MP_ROM_PTR(&mp_module_ujson) },
#else
    #define MODULE_DEF_MP_QSTR_JSON
#endif

#if (CIRCUITPY_KEYPAD)
    extern const struct _mp_obj_module_t keypad_module;
    #define MODULE_DEF_MP_QSTR_KEYPAD { MP_ROM_QSTR(MP_QSTR_keypad), MP_ROM_PTR(&keypad_module) },
#else
    #define MODULE_DEF_MP_QSTR_KEYPAD
#endif

#if (CIRCUITPY_MATH)
    extern const struct _mp_obj_module_t math_module;
    #define MODULE_DEF_MP_QSTR_MATH { MP_ROM_QSTR(MP_QSTR_math), MP_ROM_PTR(&math_module) },
#else
    #define MODULE_DEF_MP_QSTR_MATH
#endif

#if (CIRCUITPY_MICROCONTROLLER)
    extern const struct _mp_obj_module_t microcontroller_module;
    #define MODULE_DEF_MP_QSTR_MICROCONTROLLER { MP_ROM_QSTR(MP_QSTR_microcontroller), MP_ROM_PTR(&microcontroller_module) },
#else
    #define MODULE_DEF_MP_QSTR_MICROCONTROLLER
#endif

#if (CIRCUITPY_MSGPACK)
    extern const struct _mp_obj_module_t msgpack_module;
    #define MODULE_DEF_MP_QSTR_MSGPACK { MP_ROM_QSTR(MP_QSTR_msgpack), MP_ROM_PTR(&msgpack_module) },
#else
    #define MODULE_DEF_MP_QSTR_MSGPACK
#endif

#if (CIRCUITPY_NEOPIXEL_WRITE)
    extern const struct _mp_obj_module_t neopixel_write_module;
    #define MODULE_DEF_MP_QSTR_NEOPIXEL_WRITE { MP_ROM_QSTR(MP_QSTR_neopixel_write), MP_ROM_PTR(&neopixel_write_module) },
#else
    #define MODULE_DEF_MP_QSTR_NEOPIXEL_WRITE
#endif

#if (CIRCUITPY_ONEWIREIO)
    extern const struct _mp_obj_module_t onewireio_module;
    #define MODULE_DEF_MP_QSTR_ONEWIREIO { MP_ROM_QSTR(MP_QSTR_onewireio), MP_ROM_PTR(&onewireio_module) },
#else
    #define MODULE_DEF_MP_QSTR_ONEWIREIO
#endif

#if (CIRCUITPY_OS)
    extern const struct _mp_obj_module_t os_module;
    #define MODULE_DEF_MP_QSTR_OS { MP_ROM_QSTR(MP_QSTR_os), MP_ROM_PTR(&os_module) },
#else
    #define MODULE_DEF_MP_QSTR_OS
#endif

#if (CIRCUITPY_PARALLELDISPLAY)
    extern const struct _mp_obj_module_t paralleldisplay_module;
    #define MODULE_DEF_MP_QSTR_PARALLELDISPLAY { MP_ROM_QSTR(MP_QSTR_paralleldisplay), MP_ROM_PTR(&paralleldisplay_module) },
#else
    #define MODULE_DEF_MP_QSTR_PARALLELDISPLAY
#endif

#if (CIRCUITPY_PULSEIO)
    extern const struct _mp_obj_module_t pulseio_module;
    #define MODULE_DEF_MP_QSTR_PULSEIO { MP_ROM_QSTR(MP_QSTR_pulseio), MP_ROM_PTR(&pulseio_module) },
#else
    #define MODULE_DEF_MP_QSTR_PULSEIO
#endif

#if (CIRCUITPY_PWMIO)
    extern const struct _mp_obj_module_t pwmio_module;
    #define MODULE_DEF_MP_QSTR_PWMIO { MP_ROM_QSTR(MP_QSTR_pwmio), MP_ROM_PTR(&pwmio_module) },
#else
    #define MODULE_DEF_MP_QSTR_PWMIO
#endif

#if (CIRCUITPY_QRIO)
    extern const struct _mp_obj_module_t qrio_module;
    #define MODULE_DEF_MP_QSTR_QRIO { MP_ROM_QSTR(MP_QSTR_qrio), MP_ROM_PTR(&qrio_module) },
#else
    #define MODULE_DEF_MP_QSTR_QRIO
#endif

#if (CIRCUITPY_RAINBOWIO)
    extern const struct _mp_obj_module_t rainbowio_module;
    #define MODULE_DEF_MP_QSTR_RAINBOWIO { MP_ROM_QSTR(MP_QSTR_rainbowio), MP_ROM_PTR(&rainbowio_module) },
#else
    #define MODULE_DEF_MP_QSTR_RAINBOWIO
#endif

#if (CIRCUITPY_RANDOM)
    extern const struct _mp_obj_module_t random_module;
    #define MODULE_DEF_MP_QSTR_RANDOM { MP_ROM_QSTR(MP_QSTR_random), MP_ROM_PTR(&random_module) },
#else
    #define MODULE_DEF_MP_QSTR_RANDOM
#endif

#if (MICROPY_PY_URE)
    extern const struct _mp_obj_module_t mp_module_ure;
    #define MODULE_DEF_MP_QSTR_RE { MP_ROM_QSTR(MP_QSTR_re), MP_ROM_PTR(&mp_module_ure) },
#else
    #define MODULE_DEF_MP_QSTR_RE
#endif

#if (CIRCUITPY_RGBMATRIX)
    extern const struct _mp_obj_module_t rgbmatrix_module;
    #define MODULE_DEF_MP_QSTR_RGBMATRIX { MP_ROM_QSTR(MP_QSTR_rgbmatrix), MP_ROM_PTR(&rgbmatrix_module) },
#else
    #define MODULE_DEF_MP_QSTR_RGBMATRIX
#endif

#if (CIRCUITPY_ROTARYIO)
    extern const struct _mp_obj_module_t rotaryio_module;
    #define MODULE_DEF_MP_QSTR_ROTARYIO { MP_ROM_QSTR(MP_QSTR_rotaryio), MP_ROM_PTR(&rotaryio_module) },
#else
    #define MODULE_DEF_MP_QSTR_ROTARYIO
#endif

#if (CIRCUITPY_RP2PIO)
    extern const struct _mp_obj_module_t rp2pio_module;
    #define MODULE_DEF_MP_QSTR_RP2PIO { MP_ROM_QSTR(MP_QSTR_rp2pio), MP_ROM_PTR(&rp2pio_module) },
#else
    #define MODULE_DEF_MP_QSTR_RP2PIO
#endif

#if (CIRCUITPY_RTC)
    extern const struct _mp_obj_module_t rtc_module;
    #define MODULE_DEF_MP_QSTR_RTC { MP_ROM_QSTR(MP_QSTR_rtc), MP_ROM_PTR(&rtc_module) },
#else
    #define MODULE_DEF_MP_QSTR_RTC
#endif

#if (CIRCUITPY_SDCARDIO)
    extern const struct _mp_obj_module_t sdcardio_module;
    #define MODULE_DEF_MP_QSTR_SDCARDIO { MP_ROM_QSTR(MP_QSTR_sdcardio), MP_ROM_PTR(&sdcardio_module) },
#else
    #define MODULE_DEF_MP_QSTR_SDCARDIO
#endif

#if (MICROPY_PY_USELECT)
    extern const struct _mp_obj_module_t mp_module_uselect;
    #define MODULE_DEF_MP_QSTR_SELECT { MP_ROM_QSTR(MP_QSTR_select), MP_ROM_PTR(&mp_module_uselect) },
#else
    #define MODULE_DEF_MP_QSTR_SELECT
#endif

#if (CIRCUITPY_SHARPDISPLAY)
    extern const struct _mp_obj_module_t sharpdisplay_module;
    #define MODULE_DEF_MP_QSTR_SHARPDISPLAY { MP_ROM_QSTR(MP_QSTR_sharpdisplay), MP_ROM_PTR(&sharpdisplay_module) },
#else
    #define MODULE_DEF_MP_QSTR_SHARPDISPLAY
#endif

#if (CIRCUITPY_STORAGE)
    extern const struct _mp_obj_module_t storage_module;
    #define MODULE_DEF_MP_QSTR_STORAGE { MP_ROM_QSTR(MP_QSTR_storage), MP_ROM_PTR(&storage_module) },
#else
    #define MODULE_DEF_MP_QSTR_STORAGE
#endif

#if (CIRCUITPY_STRUCT)
    extern const struct _mp_obj_module_t struct_module;
    #define MODULE_DEF_MP_QSTR_STRUCT { MP_ROM_QSTR(MP_QSTR_struct), MP_ROM_PTR(&struct_module) },
#else
    #define MODULE_DEF_MP_QSTR_STRUCT
#endif

#if (CIRCUITPY_SUPERVISOR)
    extern const struct _mp_obj_module_t supervisor_module;
    #define MODULE_DEF_MP_QSTR_SUPERVISOR { MP_ROM_QSTR(MP_QSTR_supervisor), MP_ROM_PTR(&supervisor_module) },
#else
    #define MODULE_DEF_MP_QSTR_SUPERVISOR
#endif

#if (CIRCUITPY_SYNTHIO)
    extern const struct _mp_obj_module_t synthio_module;
    #define MODULE_DEF_MP_QSTR_SYNTHIO { MP_ROM_QSTR(MP_QSTR_synthio), MP_ROM_PTR(&synthio_module) },
#else
    #define MODULE_DEF_MP_QSTR_SYNTHIO
#endif

#if (CIRCUITPY_DISPLAYIO && CIRCUITPY_TERMINALIO)
    extern const struct _mp_obj_module_t terminalio_module;
    #define MODULE_DEF_MP_QSTR_TERMINALIO { MP_ROM_QSTR(MP_QSTR_terminalio), MP_ROM_PTR(&terminalio_module) },
#else
    #define MODULE_DEF_MP_QSTR_TERMINALIO
#endif

#if (CIRCUITPY_TIME)
    extern const struct _mp_obj_module_t time_module;
    #define MODULE_DEF_MP_QSTR_TIME { MP_ROM_QSTR(MP_QSTR_time), MP_ROM_PTR(&time_module) },
#else
    #define MODULE_DEF_MP_QSTR_TIME
#endif

#if (CIRCUITPY_TOUCHIO)
    extern const struct _mp_obj_module_t touchio_module;
    #define MODULE_DEF_MP_QSTR_TOUCHIO { MP_ROM_QSTR(MP_QSTR_touchio), MP_ROM_PTR(&touchio_module) },
#else
    #define MODULE_DEF_MP_QSTR_TOUCHIO
#endif

#if (CIRCUITPY_TRACEBACK)
    extern const struct _mp_obj_module_t traceback_module;
    #define MODULE_DEF_MP_QSTR_TRACEBACK { MP_ROM_QSTR(MP_QSTR_traceback), MP_ROM_PTR(&traceback_module) },
#else
    #define MODULE_DEF_MP_QSTR_TRACEBACK
#endif

#if (MODULE_ULAB_ENABLED)
    extern const struct _mp_obj_module_t ulab_user_cmodule;
    #define MODULE_DEF_MP_QSTR_ULAB { MP_ROM_QSTR(MP_QSTR_ulab), MP_ROM_PTR(&ulab_user_cmodule) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB
#endif

#if (MODULE_ULAB_ENABLED && CIRCUITPY_ULAB)
    extern const struct _mp_obj_module_t ulab_fft_module;
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_FFT { MP_ROM_QSTR(MP_QSTR_ulab_dot_fft), MP_ROM_PTR(&ulab_fft_module) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_FFT
#endif

#if (MODULE_ULAB_ENABLED && CIRCUITPY_ULAB)
    extern const struct _mp_obj_module_t ulab_linalg_module;
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_LINALG { MP_ROM_QSTR(MP_QSTR_ulab_dot_linalg), MP_ROM_PTR(&ulab_linalg_module) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_LINALG
#endif

#if (MODULE_ULAB_ENABLED && CIRCUITPY_ULAB)
    extern const struct _mp_obj_module_t ulab_numpy_module;
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_NUMPY { MP_ROM_QSTR(MP_QSTR_ulab_dot_numpy), MP_ROM_PTR(&ulab_numpy_module) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_NUMPY
#endif

#if (MODULE_ULAB_ENABLED && CIRCUITPY_ULAB)
    extern const struct _mp_obj_module_t ulab_scipy_module;
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY { MP_ROM_QSTR(MP_QSTR_ulab_dot_scipy), MP_ROM_PTR(&ulab_scipy_module) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY
#endif

#if (MODULE_ULAB_ENABLED && CIRCUITPY_ULAB)
    extern const struct _mp_obj_module_t ulab_scipy_linalg_module;
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_LINALG { MP_ROM_QSTR(MP_QSTR_ulab_dot_scipy_dot_linalg), MP_ROM_PTR(&ulab_scipy_linalg_module) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_LINALG
#endif

#if (MODULE_ULAB_ENABLED && CIRCUITPY_ULAB)
    extern const struct _mp_obj_module_t ulab_scipy_optimize_module;
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_OPTIMIZE { MP_ROM_QSTR(MP_QSTR_ulab_dot_scipy_dot_optimize), MP_ROM_PTR(&ulab_scipy_optimize_module) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_OPTIMIZE
#endif

#if (MODULE_ULAB_ENABLED && CIRCUITPY_ULAB)
    extern const struct _mp_obj_module_t ulab_scipy_signal_module;
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_SIGNAL { MP_ROM_QSTR(MP_QSTR_ulab_dot_scipy_dot_signal), MP_ROM_PTR(&ulab_scipy_signal_module) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_SIGNAL
#endif

#if (MODULE_ULAB_ENABLED && CIRCUITPY_ULAB)
    extern const struct _mp_obj_module_t ulab_scipy_special_module;
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_SPECIAL { MP_ROM_QSTR(MP_QSTR_ulab_dot_scipy_dot_special), MP_ROM_PTR(&ulab_scipy_special_module) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_SPECIAL
#endif

#if (ULAB_HAS_USER_MODULE && CIRCUITPY_ULAB)
    extern const struct _mp_obj_module_t ulab_user_module;
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_USER { MP_ROM_QSTR(MP_QSTR_ulab_dot_user), MP_ROM_PTR(&ulab_user_module) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_USER
#endif

#if (MODULE_ULAB_ENABLED && CIRCUITPY_ULAB)
    extern const struct _mp_obj_module_t ulab_utils_module;
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_UTILS { MP_ROM_QSTR(MP_QSTR_ulab_dot_utils), MP_ROM_PTR(&ulab_utils_module) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB_DOT_UTILS
#endif

#if (CIRCUITPY_USB_CDC)
    extern const struct _mp_obj_module_t usb_cdc_module;
    #define MODULE_DEF_MP_QSTR_USB_CDC { MP_ROM_QSTR(MP_QSTR_usb_cdc), MP_ROM_PTR(&usb_cdc_module) },
#else
    #define MODULE_DEF_MP_QSTR_USB_CDC
#endif

#if (CIRCUITPY_USB_HID)
    extern const struct _mp_obj_module_t usb_hid_module;
    #define MODULE_DEF_MP_QSTR_USB_HID { MP_ROM_QSTR(MP_QSTR_usb_hid), MP_ROM_PTR(&usb_hid_module) },
#else
    #define MODULE_DEF_MP_QSTR_USB_HID
#endif

#if (CIRCUITPY_USB_MIDI)
    extern const struct _mp_obj_module_t usb_midi_module;
    #define MODULE_DEF_MP_QSTR_USB_MIDI { MP_ROM_QSTR(MP_QSTR_usb_midi), MP_ROM_PTR(&usb_midi_module) },
#else
    #define MODULE_DEF_MP_QSTR_USB_MIDI
#endif

#if (CIRCUITPY_VECTORIO)
    extern const struct _mp_obj_module_t vectorio_module;
    #define MODULE_DEF_MP_QSTR_VECTORIO { MP_ROM_QSTR(MP_QSTR_vectorio), MP_ROM_PTR(&vectorio_module) },
#else
    #define MODULE_DEF_MP_QSTR_VECTORIO
#endif

#if (CIRCUITPY_WATCHDOG)
    extern const struct _mp_obj_module_t watchdog_module;
    #define MODULE_DEF_MP_QSTR_WATCHDOG { MP_ROM_QSTR(MP_QSTR_watchdog), MP_ROM_PTR(&watchdog_module) },
#else
    #define MODULE_DEF_MP_QSTR_WATCHDOG
#endif

#if (CIRCUITPY_ZLIB)
    extern const struct _mp_obj_module_t zlib_module;
    #define MODULE_DEF_MP_QSTR_ZLIB { MP_ROM_QSTR(MP_QSTR_zlib), MP_ROM_PTR(&zlib_module) },
#else
    #define MODULE_DEF_MP_QSTR_ZLIB
#endif


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR___FUTURE__ \
    MODULE_DEF_MP_QSTR__ASYNCIO \
    MODULE_DEF_MP_QSTR__BLEIO \
    MODULE_DEF_MP_QSTR__EVE \
    MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE \
    MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE_DOT_I2C_DEVICE \
    MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE_DOT_SPI_DEVICE \
    MODULE_DEF_MP_QSTR_ADAFRUIT_PIXELBUF \
    MODULE_DEF_MP_QSTR_AESIO \
    MODULE_DEF_MP_QSTR_ALARM \
    MODULE_DEF_MP_QSTR_ANALOGIO \
    MODULE_DEF_MP_QSTR_ARRAY \
    MODULE_DEF_MP_QSTR_ATEXIT \
    MODULE_DEF_MP_QSTR_AUDIOBUSIO \
    MODULE_DEF_MP_QSTR_AUDIOCORE \
    MODULE_DEF_MP_QSTR_AUDIOMIXER \
    MODULE_DEF_MP_QSTR_AUDIOMP3 \
    MODULE_DEF_MP_QSTR_AUDIOPWMIO \
    MODULE_DEF_MP_QSTR_BINASCII \
    MODULE_DEF_MP_QSTR_BITBANGIO \
    MODULE_DEF_MP_QSTR_BITMAPTOOLS \
    MODULE_DEF_MP_QSTR_BITOPS \
    MODULE_DEF_MP_QSTR_BOARD \
    MODULE_DEF_MP_QSTR_BUSIO \
    MODULE_DEF_MP_QSTR_COUNTIO \
    MODULE_DEF_MP_QSTR_DIGITALIO \
    MODULE_DEF_MP_QSTR_DISPLAYIO \
    MODULE_DEF_MP_QSTR_ERRNO \
    MODULE_DEF_MP_QSTR_FLOPPYIO \
    MODULE_DEF_MP_QSTR_FONTIO \
    MODULE_DEF_MP_QSTR_FRAMEBUFFERIO \
    MODULE_DEF_MP_QSTR_GETPASS \
    MODULE_DEF_MP_QSTR_GIFIO \
    MODULE_DEF_MP_QSTR_IMAGECAPTURE \
    MODULE_DEF_MP_QSTR_JSON \
    MODULE_DEF_MP_QSTR_KEYPAD \
    MODULE_DEF_MP_QSTR_MATH \
    MODULE_DEF_MP_QSTR_MICROCONTROLLER \
    MODULE_DEF_MP_QSTR_MSGPACK \
    MODULE_DEF_MP_QSTR_NEOPIXEL_WRITE \
    MODULE_DEF_MP_QSTR_ONEWIREIO \
    MODULE_DEF_MP_QSTR_OS \
    MODULE_DEF_MP_QSTR_PARALLELDISPLAY \
    MODULE_DEF_MP_QSTR_PULSEIO \
    MODULE_DEF_MP_QSTR_PWMIO \
    MODULE_DEF_MP_QSTR_QRIO \
    MODULE_DEF_MP_QSTR_RAINBOWIO \
    MODULE_DEF_MP_QSTR_RANDOM \
    MODULE_DEF_MP_QSTR_RE \
    MODULE_DEF_MP_QSTR_RGBMATRIX \
    MODULE_DEF_MP_QSTR_ROTARYIO \
    MODULE_DEF_MP_QSTR_RP2PIO \
    MODULE_DEF_MP_QSTR_RTC \
    MODULE_DEF_MP_QSTR_SDCARDIO \
    MODULE_DEF_MP_QSTR_SELECT \
    MODULE_DEF_MP_QSTR_SHARPDISPLAY \
    MODULE_DEF_MP_QSTR_STORAGE \
    MODULE_DEF_MP_QSTR_STRUCT \
    MODULE_DEF_MP_QSTR_SUPERVISOR \
    MODULE_DEF_MP_QSTR_SYNTHIO \
    MODULE_DEF_MP_QSTR_TERMINALIO \
    MODULE_DEF_MP_QSTR_TIME \
    MODULE_DEF_MP_QSTR_TOUCHIO \
    MODULE_DEF_MP_QSTR_TRACEBACK \
    MODULE_DEF_MP_QSTR_ULAB \
    MODULE_DEF_MP_QSTR_ULAB_DOT_FFT \
    MODULE_DEF_MP_QSTR_ULAB_DOT_LINALG \
    MODULE_DEF_MP_QSTR_ULAB_DOT_NUMPY \
    MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY \
    MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_LINALG \
    MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_OPTIMIZE \
    MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_SIGNAL \
    MODULE_DEF_MP_QSTR_ULAB_DOT_SCIPY_DOT_SPECIAL \
    MODULE_DEF_MP_QSTR_ULAB_DOT_USER \
    MODULE_DEF_MP_QSTR_ULAB_DOT_UTILS \
    MODULE_DEF_MP_QSTR_USB_CDC \
    MODULE_DEF_MP_QSTR_USB_HID \
    MODULE_DEF_MP_QSTR_USB_MIDI \
    MODULE_DEF_MP_QSTR_VECTORIO \
    MODULE_DEF_MP_QSTR_WATCHDOG \
    MODULE_DEF_MP_QSTR_ZLIB \
// MICROPY_REGISTERED_MODULES
